export const GET_ALL_FILMS = "GET_ALL_FILMS";
export const SET_ALL_FILMS = "SET_ALL_FILMS";
export const SET_FILMS_PAGES = "SET_FILMS_PAGES";
export const SET_ALL_FILMS_ERROR = "SET_ALL_FILMS_ERROR";
export const SET_ALL_FILMS_LOADING = "SET_ALL_FILMS_LOADING";
export const SET_FILMS_FILTERS = "SET_FILMS_FILTERS";
export const SET_FILMS_PAGE = "SET_FILMS_PAGE";
export const CLEAR_FILMS_LIST = "CLEAR_FILMS_LIST";