export const SET_USER_EMAIL = "SET_USER_EMAIL";
export const SET_USER_NAME = "SET_USER_NAME";
export const SET_USER_PASSWORD = "SET_USER_PASSWORD";
export const SET_USER_AVATAR = "SET_USER_AVATAR";
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";

export const CLEAR_FORM = "CLEAR_FORM";
export const SET_USER_DATA = "SET_USER_DATA";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";
export const SET_USER_IS_LOADING = "SET_USER_IS_LOADING";
export const SET_USER_ERROR = "SET_USER_ERROR";

export const SET_REGISTER_VALIDATE_ERROR = "SET_REGISTER_VALIDATE_ERROR";
export const SET_LOGIN_VALIDATE_ERROR = "SET_LOGIN_VALIDATE_ERROR";
export const SET_USER_DATA_AVATAR = "SET_USER_DATA_AVATAR";
export const USER = "USER";

export const SET_PROFILE_AVATAR = "SET_PROFILE_AVATAR";
export const SET_PROFILE_AVATAR_LOADING = "SET_PROFILE_AVATAR_LOADING";
export const SET_PROFILE_AVATAR_ERROR = "SET_PROFILE_AVATAR_ERROR";