export const SET_COMMENTS = "SET_COMMENTS";
export const SET_COMMENTS_LOADING = "SET_COMMENTS_LOADING";
export const SET_COMMENTS_ERROR = "SET_COMMENTS_ERROR";
export const CLEAR_COMMENTS = "CLEAR_COMMENTS";
export const FILM_COMMENTS = "FILM_COMMENTS";

