export const SET_COMMENTS = "SET_COMMENTS";
export const SET_COMMENTS_LOADING = "SET_COMMENTS_LOADING";
export const SET_COMMENTS_ERROR = "SET_COMMENTS_ERROR";
export const CLEAR_COMMENTS = "CLEAR_COMMENTS";
export const FILM_COMMENTS = "FILM_COMMENTS";

// COMMENTS FORM

export const SET_COMMENT_FORM_DATA = "SET_COMMENT_FORM_DATA";
export const CREATE_COMMENT_LOADING = "CREATE_COMMENT_LOADING";
export const CREATE_COMMENT_ERROR = "CREATE_COMMENT_ERROR";
export const CLEAR_COMMENT_FORM = "CLEAR_COMMENT_FORM";
export const CREATE_COMMENT = "CREATE_COMMENT";

