export const SET_FAVORITES = "SET_FAVORITES";
export const SET_FAVORITES_LOADING = "SET_FAVORITES_LOADING";
export const SET_FAVORITES_ERROR = "SET_FAVORITES_ERROR";
export const FAVORITES_ACTION = "FAVORITES_ACTION";