export const SET_FAVORITES = "SET_FAVORITES";
export const SET_USER_FAVORITES = "SET_USER_FAVORITES";
export const SET_FAVORITES_LOADING = "SET_FAVORITES_LOADING";
export const SET_FAVORITES_ERROR = "SET_FAVORITES_ERROR";
export const FAVORITES_ACTION = "FAVORITES_ACTION";

export const SET_TOGGLE_FAVORITE_ID = "SET_TOGGLE_FAVORITE_ID";
export const SET_TOGGLE_FAVORITE_LOADING = "SET_TOGGLE_FAVORITE_LOADING";
export const SET_TOGGLE_FAVORITE_ERROR = "SET_TOGGLE_FAVORITE_ERROR";
export const ADD_TO_FAVORITES_ACTION = "ADD_TO_FAVORITES_ACTION";
export const REMOVE_FROM_FAVORITES_ACTION = "REMOVE_FROM_FAVORITES_ACTION";