export const TOGGLE_FAVORITES = "TOGGLE_FAVORITES";
export const SET_FAVORITES_LOADING = "SET_FAVORITES_LOADING";
export const SET_FAVORITES_DATA = "SET_FAVORITES_DATA";
export const SET_FAVORITES_ERROR = "SET_FAVORITES_ERROR";
export const SET_USER_FAVORITES_DATA = "SET_USER_FAVORITES_DATA";
export const RESET_FAVORITES_DATA = "RESET_FAVORITES_DATA";
export const FAVORITES_ACTION = "FAVORITES_ACTION";
export const CLEAR_FAVORITES_ACTION = "CLEAR_FAVORITES_ACTION";