export const SET_USERS_LIST = "SET_USERS_LIST";
export const SET_USERS_LOADING = "SET_USERS_LOADING";
export const SET_USERS_ERROR = "SET_USERS_ERROR";
export const GET_USERS_LIST = "GET_USERS_LIST";
export const CLEAR_USERS_LIST = "CLEAR_USERS_LIST";