export const KINOPOISK_API_GENRES = {
    action: "боевик",
    fantasy: "фэнтези",
    scienceFiction: "фантастика",
    thriller: "триллер",
    war: "военный",
    detective: "детектив",
    comedy: "комедия",
    drama: "драма",
    horror: "ужасы",
    crime: "криминал",
    romance: "мелодрама",
    western: "вестерн",
    biography: 'биография',
    anime: 'аниме',
    kids: 'детский',
    animation: 'мультфильм',
    filmNoir: 'фильм-нуар',
    adult: 'для взрослых',
    documentary: 'документальный',
    history: 'история',
    concert: 'концерт',
    short: 'короткометражка',
    music: 'музыка',
    musical: 'мюзикл',
    news: 'новости',
    adventure: 'приключения',
    realityTV: 'реальное ТВ',
    family: 'семейный',
    sports: 'спорт',
    talkShow: 'ток-шоу',
    ceremony: 'церемония',
}